spring.application.name=library-management-system


spring.datasource.url=jdbc:mysql://localhost:3306/LibraryManagementSystem
spring.datasource.username=root
spring.datasource.password=SHADOW052807



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

